model_type: CoMusion
t_his: 25
t_pred: 100
eval_sample_num: 50
dtype: float32


model_specs:
  node_n: 48
  act: nn.Tanh
  dct_dim: 125
  gcn_dim: 256
  gcn_drop: 0.5
  inner_stage: 2
  outer_stage: 3
  trans_dim: 512
  trans_drop: 0.1
  trans_ff_dim: 1024
  trans_num_heads: 4
  trans_num_layers: 8


data_specs:
  dataset: h36m
  actions: all
  augmentation: 5
  stride: 10
  data_aug: true
  rota_prob: 1
  multimodal_threshold: 0.5


diff_specs:
  beta_schedule: ours
  diffuse_steps: 10
  div_k: 2
  loss_type: l1
  objective: pred_x0


learn_specs:
  batch_size: 64
  num_epoch_fix_lr: 200
  sched_policy: lambda
  train_epoch: 500
  train_lr: 0.0001
  weight_decay: 0


loss_weight_specs:
  history_weight: 1
  future_weight: 10


st_loss_specs:
  loss_weight_scale: 10


logging_specs:
  model_id: h36m
  model_path: ./results/h36m